# Generated by Django 3.1.4 on 2021-04-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('mid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('director', models.CharField(max_length=150)),
                ('writer', models.CharField(max_length=150)),
                ('production', models.CharField(max_length=200)),
                ('actors', models.TextField()),
                ('description', models.TextField()),
                ('rating', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.CharField(max_length=30)),
                ('u_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='PriorityLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hindi', models.IntegerField(default=0)),
                ('marathi', models.IntegerField(default=0)),
                ('english', models.IntegerField(default=0)),
                ('french', models.IntegerField(default=0)),
                ('german', models.IntegerField(default=0)),
                ('spanish', models.IntegerField(default=0)),
                ('russian', models.IntegerField(default=0)),
                ('italian', models.IntegerField(default=0)),
                ('japanese', models.IntegerField(default=0)),
                ('chinese', models.IntegerField(default=0)),
                ('users', models.ManyToManyField(blank=True, related_name='languages', to='users.User')),
            ],
        ),
        migrations.CreateModel(
            name='PriorityGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comedy', models.IntegerField(default=0)),
                ('adventure', models.IntegerField(default=0)),
                ('musical', models.IntegerField(default=0)),
                ('thriller', models.IntegerField(default=0)),
                ('drama', models.IntegerField(default=0)),
                ('romance', models.IntegerField(default=0)),
                ('action', models.IntegerField(default=0)),
                ('darkmovies', models.IntegerField(default=0)),
                ('fantasy', models.IntegerField(default=0)),
                ('scifi', models.IntegerField(default=0)),
                ('history', models.IntegerField(default=0)),
                ('users', models.ManyToManyField(blank=True, related_name='genres', to='users.User')),
            ],
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_name', models.CharField(max_length=64)),
                ('movies', models.ManyToManyField(blank=True, related_name='language', to='users.Movies')),
            ],
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_name', models.CharField(max_length=64)),
                ('movies', models.ManyToManyField(blank=True, related_name='genre', to='users.Movies')),
            ],
        ),
    ]
