# Generated by Django 3.1.4 on 2021-04-11 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210411_0512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='duration',
            field=models.FloatField(),
        ),
    ]
